"""
PDF export for natal and synastry reports using reportlab.

reportlab handles the full Unicode range natively (astrological symbols,
degree signs, em-dashes, curly quotes) without needing external font files.
"""
from __future__ import annotations

import io
import re

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

_PURPLE = colors.HexColor("#4a2d7a")
_LIGHT_PURPLE = colors.HexColor("#6644aa")
_ACCENT = colors.HexColor("#c8a8f8")
_GREY = colors.HexColor("#666666")
_LIGHT_GREY = colors.HexColor("#999999")
_RULE_GREY = colors.HexColor("#cccccc")


def _make_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        "AstroTitle", parent=styles["Title"],
        fontSize=20, textColor=_PURPLE, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "AstroMeta", parent=styles["Normal"],
        fontSize=10, textColor=_GREY, spaceAfter=2,
        fontName="Helvetica-Oblique",
    ))
    styles.add(ParagraphStyle(
        "AstroH2", parent=styles["Heading2"],
        fontSize=14, textColor=_LIGHT_PURPLE, spaceBefore=14, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "AstroH3", parent=styles["Heading3"],
        fontSize=12, textColor=_LIGHT_PURPLE, spaceBefore=8, spaceAfter=3,
    ))
    styles.add(ParagraphStyle(
        "AstroBody", parent=styles["Normal"],
        fontSize=11, leading=17, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "AstroBullet", parent=styles["Normal"],
        fontSize=11, leading=15, leftIndent=16, spaceAfter=3,
    ))
    styles.add(ParagraphStyle(
        "AstroFooter", parent=styles["Normal"],
        fontSize=8, textColor=_LIGHT_GREY, alignment=1,
    ))
    return styles


def _inline(text: str) -> str:
    """Convert inline markdown to reportlab XML markup."""
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"__(.+?)__", r"<b>\1</b>", text)
    text = re.sub(r"\*([^*]+)\*", r"<i>\1</i>", text)
    text = re.sub(r"(?<![_])_([^_]+)_(?![_])", r"<i>\1</i>", text)
    return text


def _md_to_flowables(text: str, styles) -> list:
    """Parse markdown text into reportlab Platypus flowables."""
    flowables = []
    blocks = re.split(r"\n{2,}", text.strip())

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        if block.startswith("### "):
            flowables.append(Paragraph(block[4:], styles["AstroH3"]))
        elif block.startswith("## "):
            flowables.append(Paragraph(block[3:], styles["AstroH2"]))
        elif block.startswith("# "):
            flowables.append(Paragraph(block[2:], styles["AstroH2"]))
        elif re.search(r"^[-*] ", block, re.MULTILINE):
            for line in block.splitlines():
                m = re.match(r"^[-*] (.+)", line.strip())
                if m:
                    flowables.append(
                        Paragraph("• " + _inline(m.group(1)), styles["AstroBullet"])
                    )
        elif re.match(r"^\d+\. ", block):
            for line in block.splitlines():
                m = re.match(r"^(\d+)\. (.+)", line.strip())
                if m:
                    flowables.append(
                        Paragraph(f"{m.group(1)}. {_inline(m.group(2))}", styles["AstroBody"])
                    )
        elif re.match(r"^\*\*[^*]+\*\*$", block):
            # Bold-only line used as section heading (e.g. **1. Section Name**)
            heading = re.sub(r"^\*\*(.+)\*\*$", r"\1", block)
            flowables.append(Paragraph(heading, styles["AstroH2"]))
        else:
            for line in block.splitlines():
                line = line.strip()
                if line:
                    flowables.append(Paragraph(_inline(line), styles["AstroBody"]))

    return flowables


def _footer(styles) -> list:
    return [
        Spacer(1, 16),
        HRFlowable(width="100%", thickness=0.5, color=_RULE_GREY),
        Spacer(1, 4),
        Paragraph("Generated by Personal Astrologer Agent · For personal use only", styles["AstroFooter"]),
    ]


def natal_pdf(result: dict) -> bytes:
    """Return PDF bytes for a natal chart reading."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=20 * mm, leftMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
        title=f"Natal Reading — {result.get('full_name', '')}",
        author="Personal Astrologer Agent",
    )
    styles = _make_styles()
    story: list = []

    story.append(Paragraph(f"Natal Chart Reading — {result.get('full_name', '')}", styles["AstroTitle"]))
    story.append(Paragraph(
        f"Born {result.get('parsed_dob', '')} · {result.get('birth_location', '')}",
        styles["AstroMeta"],
    ))
    current_dt = (result.get("parsed_current_datetime") or "")[:10]
    story.append(Paragraph(
        f"Current location: {result.get('current_location', '')} · Reading date: {current_dt}",
        styles["AstroMeta"],
    ))
    if result.get("report_focus"):
        story.append(Paragraph(f"Focus: {result['report_focus']}", styles["AstroMeta"]))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.5, color=_ACCENT))
    story.append(Spacer(1, 12))

    report_text = result.get("final_report") or ""
    story.extend(_md_to_flowables(report_text, styles))
    story.extend(_footer(styles))

    doc.build(story)
    return buf.getvalue()


def synastry_pdf(syn: dict) -> bytes:
    """Return PDF bytes for a synastry compatibility reading."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=20 * mm, leftMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
        title=f"Synastry — {syn.get('name_a', '')} & {syn.get('name_b', '')}",
        author="Personal Astrologer Agent",
    )
    styles = _make_styles()
    story: list = []

    story.append(Paragraph(
        f"Synastry: {syn.get('name_a', '')} &amp; {syn.get('name_b', '')}",
        styles["AstroTitle"],
    ))
    story.append(Paragraph(
        f"{syn.get('name_a', '')}: {syn.get('dob_a', '')} · {syn.get('loc_a', '')}",
        styles["AstroMeta"],
    ))
    story.append(Paragraph(
        f"{syn.get('name_b', '')}: {syn.get('dob_b', '')} · {syn.get('loc_b', '')}",
        styles["AstroMeta"],
    ))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.5, color=_ACCENT))
    story.append(Spacer(1, 12))

    report_text = syn.get("report") or ""
    story.extend(_md_to_flowables(report_text, styles))
    story.extend(_footer(styles))

    doc.build(story)
    return buf.getvalue()
